// DomainLayerTests - Testes unitários para os casos de uso do domínio
// Usando Cuckoo para mocks automáticos

import XCTest
import Cuckoo
@testable import MeetingAssistantCore

final class DomainLayerTests: XCTestCase {
    var mockRecordingRepo: MockRecordingRepository!
    var mockAudioFileRepo: MockAudioFileRepository!
    var mockMeetingRepo: MockMeetingRepository!
    var mockTranscriptionRepo: MockTranscriptionRepository!
    var mockTranscriptionStorageRepo: MockTranscriptionStorageRepository!
    var mockPostProcessingRepo: MockPostProcessingRepository!

    override func setUp() {
        super.setUp()
        mockRecordingRepo = MockRecordingRepository()
        mockAudioFileRepo = MockAudioFileRepository()
        mockMeetingRepo = MockMeetingRepository()
        mockTranscriptionRepo = MockTranscriptionRepository()
        mockTranscriptionStorageRepo = MockTranscriptionStorageRepository()
        mockPostProcessingRepo = MockPostProcessingRepository()
    }

    // MARK: - StartRecordingUseCase Tests

    func testStartRecordingSuccess() async throws {
        // Given
        let useCase = StartRecordingUseCase(
            recordingRepository: mockRecordingRepo,
            audioFileRepository: mockAudioFileRepo,
            meetingRepository: mockMeetingRepo
        )
        let meeting = MeetingEntity(app: .googleMeet)
        let expectedURL = URL(fileURLWithPath: "/tmp/test.wav")

        stub(mockRecordingRepo) { stub in
            when(stub.hasPermission()).then { _ in true }
            when(stub.startRecording(to: any(), retryCount: any())).then { _ in }
        }
        stub(mockAudioFileRepo) { stub in
            when(stub.generateAudioFileURL(for: any())).thenReturn(expectedURL)
        }
        stub(mockMeetingRepo) { stub in
            when(stub.updateMeeting(any())).then { _ in }
        }

        // When
        let resultURL = try await useCase.execute(for: meeting)

        // Then
        XCTAssertEqual(resultURL, expectedURL)
        verify(mockRecordingRepo).hasPermission()
        verify(mockRecordingRepo).startRecording(to: equal(to: expectedURL), retryCount: 3)
        verify(mockMeetingRepo).updateMeeting(any())
    }

    func testStartRecordingPermissionDenied() async {
        // Given
        let useCase = StartRecordingUseCase(
            recordingRepository: mockRecordingRepo,
            audioFileRepository: mockAudioFileRepo,
            meetingRepository: mockMeetingRepo
        )
        let meeting = MeetingEntity(app: .googleMeet)

        stub(mockRecordingRepo) { stub in
            when(stub.hasPermission()).then { _ in false }
        }

        // When/Then
        do {
            _ = try await useCase.execute(for: meeting)
            XCTFail("Should throw permissionDenied")
        } catch RecordingError.permissionDenied {
            // Success
        } catch {
            XCTFail("Unexpected error: \(error)")
        }
    }

    // MARK: - TranscribeAudioUseCase Tests

    func testTranscribeAudioSuccess() async throws {
        // Given
        let useCase = TranscribeAudioUseCase(
            transcriptionRepository: mockTranscriptionRepo,
            transcriptionStorageRepository: mockTranscriptionStorageRepo,
            postProcessingRepository: mockPostProcessingRepo
        )
        let meeting = MeetingEntity(app: .googleMeet)
        let audioURL = URL(fileURLWithPath: "/tmp/test.wav")
        let response = DomainTranscriptionResponse(
            text: "Hello world",
            language: "en",
            durationSeconds: 5.0,
            model: "test-model",
            processedAt: "now"
        )

        stub(mockTranscriptionRepo) { stub in
            when(stub.healthCheck()).then { _ in true }
            when(stub.transcribe(audioURL: any())).thenReturn(response)
        }
        stub(mockTranscriptionStorageRepo) { stub in
            when(stub.saveTranscription(any())).then { _ in }
        }

        // When
        let transcription = try await useCase.execute(audioURL: audioURL, meeting: meeting)

        // Then
        XCTAssertEqual(transcription.text, "Hello world")
        XCTAssertEqual(transcription.meeting.id, meeting.id)
        verify(mockTranscriptionRepo).healthCheck()
        verify(mockTranscriptionRepo).transcribe(audioURL: equal(to: audioURL))
        verify(mockTranscriptionStorageRepo).saveTranscription(any())
    }
}

// MARK: - Manual Mocks (Until Cuckoo generator is run)
// Note: In a real project, these would be generated by Cuckoo CLI

class MockRecordingRepository: RecordingRepository, Mock {
    typealias MocksType = RecordingRepository
    let cuckoo_manager = Cuckoo.MockManager(hasParent: false)

    func startRecording(to outputURL: URL, retryCount: Int) async throws {
        return try await cuckoo_manager.callThrows("startRecording(to:retryCount:)",
            parameters: (outputURL, retryCount),
            escapingParameters: (outputURL, retryCount))
    }

    func stopRecording() async throws -> URL? {
        return try await cuckoo_manager.callThrows("stopRecording()", parameters: (), escapingParameters: ())
    }

    func hasPermission() async -> Bool {
        return await cuckoo_manager.call("hasPermission()", parameters: (), escapingParameters: ())
    }

    func requestPermission() async {
        return await cuckoo_manager.call("requestPermission()", parameters: (), escapingParameters: ())
    }

    func getPermissionState() -> DomainPermissionState {
        return cuckoo_manager.call("getPermissionState()", parameters: (), escapingParameters: ())
    }

    func openSettings() async {
        return await cuckoo_manager.call("openSettings()", parameters: (), escapingParameters: ())
    }
}

class MockAudioFileRepository: AudioFileRepository, Mock {
    typealias MocksType = AudioFileRepository
    let cuckoo_manager = Cuckoo.MockManager(hasParent: false)

    func saveAudioFile(from sourceURL: URL, to destinationURL: URL) async throws {
        return try await cuckoo_manager.callThrows("saveAudioFile(from:to:)", parameters: (sourceURL, destinationURL), escapingParameters: (sourceURL, destinationURL))
    }

    func deleteAudioFile(at url: URL) async throws {
        return try await cuckoo_manager.callThrows("deleteAudioFile(at:)", parameters: (url), escapingParameters: (url))
    }

    func audioFileExists(at url: URL) -> Bool {
        return cuckoo_manager.call("audioFileExists(at:)", parameters: (url), escapingParameters: (url))
    }

    func generateAudioFileURL(for meetingId: UUID) -> URL {
        return cuckoo_manager.call("generateAudioFileURL(for:)", parameters: (meetingId), escapingParameters: (meetingId))
    }

    func listAudioFiles() async throws -> [URL] {
        return try await cuckoo_manager.callThrows("listAudioFiles()", parameters: (), escapingParameters: ())
    }
}

class MockMeetingRepository: MeetingRepository, Mock {
    typealias MocksType = MeetingRepository
    let cuckoo_manager = Cuckoo.MockManager(hasParent: false)

    func saveMeeting(_ meeting: MeetingEntity) async throws {
        return try await cuckoo_manager.callThrows("saveMeeting(_:)", parameters: (meeting), escapingParameters: (meeting))
    }

    func fetchMeeting(by id: UUID) async throws -> MeetingEntity? {
        return try await cuckoo_manager.callThrows("fetchMeeting(by:)", parameters: (id), escapingParameters: (id))
    }

    func fetchAllMeetings() async throws -> [MeetingEntity] {
        return try await cuckoo_manager.callThrows("fetchAllMeetings()", parameters: (), escapingParameters: ())
    }

    func deleteMeeting(by id: UUID) async throws {
        return try await cuckoo_manager.callThrows("deleteMeeting(by:)", parameters: (id), escapingParameters: (id))
    }

    func updateMeeting(_ meeting: MeetingEntity) async throws {
        return try await cuckoo_manager.callThrows("updateMeeting(_:)", parameters: (meeting), escapingParameters: (meeting))
    }
}

class MockTranscriptionRepository: TranscriptionRepository, Mock {
    typealias MocksType = TranscriptionRepository
    let cuckoo_manager = Cuckoo.MockManager(hasParent: false)

    func healthCheck() async throws -> Bool {
        return try await cuckoo_manager.callThrows("healthCheck()", parameters: (), escapingParameters: ())
    }

    func fetchServiceStatus() async throws -> DomainServiceStatusResponse {
        return try await cuckoo_manager.callThrows("fetchServiceStatus()", parameters: (), escapingParameters: ())
    }

    func transcribe(audioURL: URL) async throws -> DomainTranscriptionResponse {
        return try await cuckoo_manager.callThrows("transcribe(audioURL:)", parameters: (audioURL), escapingParameters: (audioURL))
    }
}

class MockTranscriptionStorageRepository: TranscriptionStorageRepository, Mock {
    typealias MocksType = TranscriptionStorageRepository
    let cuckoo_manager = Cuckoo.MockManager(hasParent: false)

    func saveTranscription(_ transcription: TranscriptionEntity) async throws {
        return try await cuckoo_manager.callThrows("saveTranscription(_:)", parameters: (transcription), escapingParameters: (transcription))
    }

    func fetchTranscription(by id: UUID) async throws -> TranscriptionEntity? {
        return try await cuckoo_manager.callThrows("fetchTranscription(by:)", parameters: (id), escapingParameters: (id))
    }

    func fetchTranscriptions(for meetingId: UUID) async throws -> [TranscriptionEntity] {
        return try await cuckoo_manager.callThrows("fetchTranscriptions(for:)", parameters: (meetingId), escapingParameters: (meetingId))
    }

    func fetchAllTranscriptions() async throws -> [TranscriptionEntity] {
        return try await cuckoo_manager.callThrows("fetchAllTranscriptions()", parameters: (), escapingParameters: ())
    }

    func deleteTranscription(by id: UUID) async throws {
        return try await cuckoo_manager.callThrows("deleteTranscription(by:)", parameters: (id), escapingParameters: (id))
    }

    func updateTranscription(_ transcription: TranscriptionEntity) async throws {
        return try await cuckoo_manager.callThrows("updateTranscription(_:)", parameters: (transcription), escapingParameters: (transcription))
    }
}

class MockPostProcessingRepository: PostProcessingRepository, Mock {
    typealias MocksType = PostProcessingRepository
    let cuckoo_manager = Cuckoo.MockManager(hasParent: false)

    func processTranscription(_ transcription: String) async throws -> String {
        return try await cuckoo_manager.callThrows("processTranscription(_:)", parameters: (transcription), escapingParameters: (transcription))
    }

    func processTranscription(_ transcription: String, with prompt: DomainPostProcessingPrompt) async throws -> String {
        return try await cuckoo_manager.callThrows("processTranscription(_:with:)", parameters: (transcription, prompt), escapingParameters: (transcription, prompt))
    }
}