// Re-export internal modules so app code can continue to `import MeetingAssistantCore`.

@_exported import MeetingAssistantCoreAI
@_exported import MeetingAssistantCoreAudio
@_exported import MeetingAssistantCoreCommon
@_exported import MeetingAssistantCoreData
@_exported import MeetingAssistantCoreDomain
@_exported import MeetingAssistantCoreInfrastructure
@_exported import MeetingAssistantCoreUI

public typealias ShortcutTelemetry = MeetingAssistantCoreCommon.ShortcutTelemetry
public typealias ShortcutTelemetryEvent = MeetingAssistantCoreCommon.ShortcutTelemetryEvent
public typealias ShortcutTelemetryEventName = MeetingAssistantCoreCommon.ShortcutTelemetryEventName
public typealias ShortcutTelemetryLevel = MeetingAssistantCoreCommon.ShortcutTelemetryLevel
public typealias ShortcutTelemetryRecord = MeetingAssistantCoreCommon.ShortcutTelemetryRecord

// Re-export shortcut input types for convenience
public typealias ShortcutInputEvent = MeetingAssistantCoreInfrastructure.ShortcutInputEvent
public typealias ShortcutInputEventKind = MeetingAssistantCoreInfrastructure.ShortcutInputEventKind
public typealias ShortcutInputBackend = MeetingAssistantCoreInfrastructure.ShortcutInputBackend
public typealias MockShortcutInputBackend = MeetingAssistantCoreInfrastructure.MockShortcutInputBackend
