name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  test:
    name: Lint & Test
    runs-on: macos-14
    
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@c51a66b42363123fa82a6cfe02c60af4281dab93 # v1
        with:
          xcode-version: '16.2'

        
      - name: Install Tools
        run: brew install swiftlint swiftformat
        
      - name: Lint
        run: make lint
        
      - name: Check Formatting
        run: swiftformat --lint --config .swiftformat App Packages/MeetingAssistantCore/Sources
        
      - name: Run Tests
        run: make ci-test

  danger:
    name: Danger CI
    if: github.event_name == 'pull_request'
    runs-on: macos-14
    permissions:
      pull-requests: write
      contents: read
      statuses: write
      issues: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@c51a66b42363123fa82a6cfe02c60af4281dab93 # v1
        with:
          xcode-version: '16.2'

        
      - name: Install Danger
        run: brew install danger/tap/danger-swift
        
      - name: Run Danger
        run: make danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
